#server:
#  port: 5432
#
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5332/test
#    username: postgres-0
#    password: springlibrarydeme
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show_sql: true
#
#  main:
#    web-application-type: servlet